name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: clojure:openjdk-17-tools-deps

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    ## This is optional but will speed up clojure steps
    - name: Cache mvn/git deps
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      id: cache-deps
      with:
        path: |
          /root/.gitlibs
          /root/.m2
        key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}

    ## The clojure tools-deps image has very little installed software,
    ## install minimum requirements for the foundationdb one
    - name: Install curl
      run: |
        apt-get update
        apt-get -qyy install curl sudo

    - name: Install foundationdb
      uses: foundationdb-rs/foundationdb-actions-install@94c35a52d4a5fa82d8a5403850247e15b65e5066 # v2.3.0
      with:
        version: 7.3.57

    - name: Check
      run: clojure -T:project check

    - name: Test
      run: clojure -T:project test

    - name: Lint
      run: clojure -T:project lint

    - name: Format
      run: clojure -T:project format-check
