name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: clojure:openjdk-17-tools-deps-slim-bullseye

    steps:
    - uses: actions/checkout@v3.0.2
    - name: Check
      run: clojure -X:project check
    - name: Lint
      run: clojure -X:project lint
    - name: Format
      run: clojure -X:project format-check
